{{- if .Values.publicPersistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "web.publicPvcName" . }}
  namespace: {{ .Release.Namespace }}
{{- with .Values.publicPersistence.annotations  }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
  labels:
    app: {{ template "web.fullname" . }}
spec:
  {{- range .Values.publicPersistence.accessModes }}
  accessModes:
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.publicPersistence.size | quote }}
{{- if .Values.publicPersistence.storageClass }}
{{- if (eq "-" .Values.publicPersistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.publicPersistence.storageClass }}"
{{- end }}
{{- end }}
{{- end }}