{{- if not .Values.configSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cms.configSecretName" . }}
type: Opaque
{{- with .Values.config }}
stringData:
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}
